/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshPhongMaterial } from 'three'

export default function Cone(props) {
  const { nodes, materials } = useGLTF('/cone.glb')
  return (
    <group {...props} dispose={null} scale={[0.0015, 0.0015, 0.0015]} position={[0, 0, 1.5]}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} >
        <meshStandardMaterial attach={"material"} color={0x373cdb}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/cone.glb')
